# =============================================================================
# RuboCop Configuration - MODERN INDUSTRIAL STANDARD
# Last Updated: 2026-01-10
# =============================================================================

plugins:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rake

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.4
  Exclude:
    - 'vendor/**/*'
    - '_site/**/*'
    - 'node_modules/**/*'
    - 'bin/jekyll'
    - 'bin/bootstrap'
    - 'Gemfile.lock'

# =============================================================================
# Style - MODERN RUBY STANDARDS
# =============================================================================

# Documentation (required for public APIs)
Style/Documentation:
  Enabled: true
  Exclude:
    - 'tests/unit/**/*'
    - 'Rakefile'
    - 'Gemfile'

# Modern Ruby syntax enforcement
Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
  EnforcedShorthandSyntax: always

Style/SymbolArray:
  EnforcedStyle: percent

Style/WordArray:
  EnforcedStyle: percent

# Modern patterns (Industrial standard)
Style/AndOr:
  Enabled: true
  EnforcedStyle: always

Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: compact

Style/Lambda:
  EnforcedStyle: literal

Style/NumericPredicate:
  Enabled: true

Style/ParallelAssignment:
  Enabled: true

Style/PreferredHashMethods:
  EnforcedStyle: short

Style/RaiseArgs:
  EnforcedStyle: compact

Style/RedundantReturn:
  Enabled: true
  AllowMultipleReturnValues: true

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

Style/SafeNavigation:
  Enabled: true

Style/SignalException:
  EnforcedStyle: only_raise

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex

# =============================================================================
# Metrics - BALANCED FOR PRODUCTION
# =============================================================================

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'tests/unit/**/*'
    - 'Rakefile'

Layout/LineLength:
  Max: 120
  AllowedPatterns: ['\A\s*#']

Metrics/MethodLength:
  Max: 15 # Practical for real methods

Metrics/ClassLength:
  Max: 120 # Reasonable class size

Metrics/ModuleLength:
  Max: 120

Metrics/ParameterLists:
  Max: 4
  MaxOptionalParameters: 3

Metrics/AbcSize:
  Max: 15 # Practical for real-world code

Metrics/CyclomaticComplexity:
  Max: 8 # Balanced complexity

Metrics/PerceivedComplexity:
  Max: 10 # Human-perceived complexity

# =============================================================================
# Lint - MODERN ERROR PREVENTION
# =============================================================================

Lint/AmbiguousBlockAssociation:
  Enabled: true

Lint/AmbiguousOperator:
  Enabled: true

Lint/AssignmentInCondition:
  Enabled: true

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'tests/unit/config_spec.rb'
    - 'tests/unit/front_matter_spec.rb'

Lint/DeprecatedClassMethods:
  Enabled: true

Lint/DuplicateMethods:
  Enabled: true

Lint/EmptyExpression:
  Enabled: true

Lint/LiteralAsCondition:
  Enabled: true

Lint/RequireParentheses:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: true
  AllowUnusedKeywordArguments: true

Lint/UnusedMethodArgument:
  Enabled: true
  AllowUnusedKeywordArguments: true

Lint/UselessAccessModifier:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Lint/Void:
  Enabled: true

# =============================================================================
# Performance - ALL ENABLED
# =============================================================================

Performance/Casecmp:
  Enabled: true

Performance/Count:
  Enabled: true

Performance/Detect:
  Enabled: true

Performance/RangeInclude:
  Enabled: true

Performance/RedundantMerge:
  Enabled: true

Performance/RegexpMatch:
  Enabled: true

Performance/ReverseEach:
  Enabled: true

Performance/Size:
  Enabled: true

Performance/StringReplacement:
  Enabled: true

Performance/TimesMap:
  Enabled: true

# =============================================================================
# RSpec - PRACTICAL TESTING STANDARDS
# =============================================================================

RSpec/ExampleLength:
  Max: 15 # Adequate for integration tests

RSpec/MultipleExpectations:
  Max: 5 # Practical for feature tests

RSpec/NestedGroups:
  Max: 4 # Allow reasonable nesting

RSpec/DescribeClass:
  Exclude:
    - 'tests/unit/config_spec.rb'
    - 'tests/unit/data_files_spec.rb'
    - 'tests/unit/front_matter_spec.rb'
    - 'tests/unit/security_spec.rb'
    - 'tests/unit/layouts_spec.rb'
    - 'tests/unit/accessibility_spec.rb'

RSpec/LeakyConstantDeclaration:
  Exclude:
    - 'tests/unit/config_spec.rb'
    - 'tests/unit/front_matter_spec.rb'

RSpec/MultipleDescribes:
  Exclude:
    - 'tests/unit/config_spec.rb'
    - 'tests/unit/layouts_spec.rb'

RSpec/BeEql:
  Enabled: true

RSpec/DescribedClass:
  Enabled: true

RSpec/EmptyExampleGroup:
  Enabled: true

RSpec/ExpectActual:
  Enabled: true

RSpec/InstanceVariable:
  Enabled: true

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/PredicateMatcher:
  Enabled: true

RSpec/VerifiedDoubles:
  Enabled: true

# =============================================================================
# Layout - MODERN FORMATTING
# =============================================================================

Layout/EndOfLine:
  Enabled: false # Windows compatibility

Layout/EmptyLines:
  Enabled: true

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true
