# =============================================================================
# RuboCop Configuration - BLEEDING-EDGE STRICTEST
# Last Updated: 2026-01-10
# =============================================================================

plugins:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rake

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.4
  Exclude:
    - 'vendor/**/*'
    - '_site/**/*'
    - 'node_modules/**/*'
    - 'bin/jekyll'
    - 'bin/bootstrap'
    - 'Gemfile.lock'

# =============================================================================
# Style - STRICTEST
# =============================================================================

# Documentation - enabled for all code (STRICT)
Style/Documentation:
  Enabled: true
  Exclude:
    - 'tests/unit/**/*'
    - 'Rakefile'
    - 'Gemfile'

# Frozen string literal required (MANDATORY)
Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

# String literals - single quotes preferred
Style/StringLiterals:
  EnforcedStyle: single_quotes

# Hash syntax - modern Ruby 3.x style
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
  EnforcedShorthandSyntax: always

# Symbol array - use %i[]
Style/SymbolArray:
  EnforcedStyle: percent

# Word array - use %w[]
Style/WordArray:
  EnforcedStyle: percent

# NEW STRICT STYLE RULES
Style/AndOr:
  Enabled: true
  EnforcedStyle: always

Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: compact

Style/CollectionMethods:
  Enabled: true

Style/Lambda:
  EnforcedStyle: literal

Style/NegatedIf:
  Enabled: true

Style/NegatedWhile:
  Enabled: true

Style/NumericPredicate:
  Enabled: true

Style/ParallelAssignment:
  Enabled: true

Style/PercentLiteralDelimiters:
  Enabled: true

Style/PreferredHashMethods:
  EnforcedStyle: short

Style/RaiseArgs:
  EnforcedStyle: compact

Style/RedundantReturn:
  Enabled: true
  AllowMultipleReturnValues: false

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: false

Style/SafeNavigation:
  Enabled: true

Style/Send:
  Enabled: true

Style/SignalException:
  EnforcedStyle: only_raise

Style/SingleLineBlockParams:
  Enabled: true

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex

# =============================================================================
# Metrics - STRICTEST LIMITS
# =============================================================================

# Block length - relaxed for specs/Rakefile only
Metrics/BlockLength:
  Max: 25
  Exclude:
    - 'tests/unit/**/*'
    - 'Rakefile'

# Line length - 100 chars max (STRICT)
Layout/LineLength:
  Max: 100
  AllowedPatterns: ['\A\s*#']

# Method length - VERY strict
Metrics/MethodLength:
  Max: 8 # Reduced from 10

# Class length - STRICT
Metrics/ClassLength:
  Max: 80 # Reduced from 100

# Module length - NEW
Metrics/ModuleLength:
  Max: 100

# Parameter lists - NEW
Metrics/ParameterLists:
  Max: 3
  MaxOptionalParameters: 2

# ABC size - complexity metric (STRICTEST)
Metrics/AbcSize:
  Max: 8 # Reduced from 10

# Cyclomatic Complexity (STRICTEST)
Metrics/CyclomaticComplexity:
  Max: 4 # Reduced from 5

# Perceived Complexity (STRICTEST)
Metrics/PerceivedComplexity:
  Max: 5 # Reduced from 6

# =============================================================================
# Lint - STRICTEST
# =============================================================================

Lint/AmbiguousBlockAssociation:
  Enabled: true

Lint/AmbiguousOperator:
  Enabled: true

Lint/AssignmentInCondition:
  Enabled: true

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'tests/unit/config_spec.rb'
    - 'tests/unit/front_matter_spec.rb'

Lint/DeprecatedClassMethods:
  Enabled: true

Lint/DuplicateMethods:
  Enabled: true

Lint/EachWithObjectArgument:
  Enabled: true

Lint/EmptyExpression:
  Enabled: true

Lint/LiteralAsCondition:
  Enabled: true

Lint/Loop:
  Enabled: true

Lint/ParenthesesAsGroupedExpression:
  Enabled: true

Lint/RequireParentheses:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: true

Lint/UnderscorePrefixedVariableName:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: true
  AllowUnusedKeywordArguments: false

Lint/UnusedMethodArgument:
  Enabled: true
  AllowUnusedKeywordArguments: false

Lint/UselessAccessModifier:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Lint/Void:
  Enabled: true

# =============================================================================
# Performance - ALL ENABLED
# =============================================================================

Performance/Casecmp:
  Enabled: true

Performance/Count:
  Enabled: true

Performance/Detect:
  Enabled: true

Performance/RangeInclude:
  Enabled: true

Performance/RedundantMerge:
  Enabled: true

Performance/RegexpMatch:
  Enabled: true

Performance/ReverseEach:
  Enabled: true

Performance/Size:
  Enabled: true

Performance/StringReplacement:
  Enabled: true

Performance/TimesMap:
  Enabled: true

# =============================================================================
# RSpec - STRICTEST SETTINGS
# =============================================================================

RSpec/ExampleLength:
  Max: 8 # Reduced from 10

RSpec/MultipleExpectations:
  Max: 2

RSpec/NestedGroups:
  Max: 3

RSpec/DescribeClass:
  Exclude:
    - 'tests/unit/config_spec.rb'
    - 'tests/unit/data_files_spec.rb'
    - 'tests/unit/front_matter_spec.rb'
    - 'tests/unit/security_spec.rb'
    - 'tests/unit/layouts_spec.rb'
    - 'tests/unit/accessibility_spec.rb'

RSpec/LeakyConstantDeclaration:
  Exclude:
    - 'tests/unit/config_spec.rb'
    - 'tests/unit/front_matter_spec.rb'

RSpec/MultipleDescribes:
  Exclude:
    - 'tests/unit/config_spec.rb'
    - 'tests/unit/layouts_spec.rb'

# NEW STRICT RSpec RULES
RSpec/BeEql:
  Enabled: true

RSpec/DescribedClass:
  Enabled: true

RSpec/EmptyExampleGroup:
  Enabled: true

RSpec/ExpectActual:
  Enabled: true

RSpec/InstanceVariable:
  Enabled: true

RSpec/IteratedExpectation:
  Enabled: true

RSpec/LetSetup:
  Enabled: true

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/PredicateMatcher:
  Enabled: true

RSpec/VerifiedDoubles:
  Enabled: true

# =============================================================================
# Layout - STRICT FORMATTING
# =============================================================================

Layout/EndOfLine:
  Enabled: false # Windows compatibility

Layout/EmptyLines:
  Enabled: true

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true
