module Jekyll
  module AmpFilter
    # Use global hook to process after rendering
    Jekyll::Hooks.register [:posts, :pages], :post_render do |doc|
      next unless doc.output.match?(/<img/)

      require 'fastimage'

      # Regex to find img tags.
      # Note: This is a simple regex for standard kramdown output.
      # It captures the whole tag and attributes roughly.
      doc.output.gsub!(/<img\s+(.*?)>/i) do |match|
        attrs = {}
        # Parse attributes
        ::Regexp.last_match(1).scan(/([a-z]+)="([^"]*)"/i) do |k, v|
          attrs[k.downcase] = v
        end

        src = attrs['src']
        alt = attrs['alt'] || ''
        title = attrs['title']

        # If it's already amp-img (unlikely with just <img regex, but safety first)
        next match if match.include?('amp-img')

        # Skip remote images (we can't easily size them during build without network)
        if /^http/.match?(src)
          warn "Warning: Remote image found in #{doc.path}: #{src}. Please turn this into <amp-img> manually with dimensions."
          next match
        end

        # Resolve local path
        # Assuming src starts with / means it is relative to site source
        # If relative, it might be tricky, but kramdown usually outputs relative to base or absolute.
        # Let's assume absolute path from root for now as per common Jekyll practice (/assets/img/...)

        local_path = File.join(doc.site.source, src)

        # Check if file exists
        unless File.exist?(local_path)
          warn "Warning: Image not found at #{local_path} in #{doc.path}"
          next match
        end

        # Get dimensions
        width, height = FastImage.size(local_path)

        unless width && height
          warn "Warning: Could not determine dimensions for #{local_path}"
          next match
        end

        # Check for WebP variant
        # Generated by our optimize-images.js: same path but .webp
        webp_path = local_path.sub(/\.[^.]+$/, '.webp')
        webp_src = src.sub(/\.[^.]+$/, '.webp')

        has_webp = File.exist?(webp_path)

        # Construct AMP HTML
        # Layout responsive is usually best for blog posts

        title_attr = title ? "title=\"#{title}\"" : ''

        if has_webp
          # AMP with WebP preference and fallback
          <<~HTML.strip
            <amp-img src="#{webp_src}" width="#{width}" height="#{height}" layout="responsive" alt="#{alt}" #{title_attr}>
              <amp-img fallback src="#{src}" width="#{width}" height="#{height}" layout="responsive" alt="#{alt}" #{title_attr}></amp-img>
            </amp-img>
          HTML
        else
          # Standard AMP img
          "<amp-img src=\"#{src}\" width=\"#{width}\" height=\"#{height}\" layout=\"responsive\" alt=\"#{alt}\" #{title_attr}></amp-img>"
        end
      end
    end
  end
end
