name: Feature Request
description: Suggest a new feature or enhancement
title: '[Feature]: '
labels: ['enhancement']
assignees:
  - syafiqhadzir

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description:
        Is your feature request related to a problem? Please describe.
      placeholder:
        A clear and concise description of what the problem is. Ex. I'm always
        frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description:
        Describe any alternative solutions or features you've considered.
      placeholder: Other approaches you've thought about...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Important
        - Critical

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description:
        Any other context, mockups, or screenshots about the feature request.
